import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const root = new URL('../', import.meta.url);
const pkg = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
let html = await readFile(new URL('wasm-migration/oracle/sudoku.html', root), 'utf8');
const wasm = await readFile(new URL('wasm-migration/build/sudoku-techniques.wasm', root));
assert.ok(WebAssembly.validate(wasm), 'Build the WASM engine first');
const adapter = (await readFile(new URL('wasm-migration/bridge/sudoku-wasm-adapter.js', root), 'utf8')).replace(/^export /gm, '');
let runtime = await readFile(new URL('wasm-migration/app/runtime.js', root), 'utf8');
runtime = runtime.replace('/* ADAPTER */', () => adapter).replace('/* WASM_BASE64 */', () => JSON.stringify(wasm.toString('base64')));
assert.ok(!runtime.includes('</script'), 'Embedded runtime must not terminate the HTML script');
function replaceOnce(from, to) {
  assert.equal(html.split(from).length, 2, `Expected exactly one integration marker: ${from}`);
  html = html.replace(from, () => to);
}
const next = 'function findNextStep(grid, getCands, order, givenGrid, validator) {';
replaceOnce(next, runtime + '\n' + next + '\n  const accelerated = WASM_RUNTIME.next(grid, getCands, order, givenGrid, validator);\n  if (accelerated !== undefined) return accelerated;');
const all = 'function findAllAvailableSteps(grid, getCands, givenGrid, validator) {';
replaceOnce(all, all + '\n  const accelerated = WASM_RUNTIME.all(grid, getCands, givenGrid, validator);\n  if (accelerated !== undefined) return accelerated;');
html = html.replace('<head>', `<head>\n<!-- Generated by scripts/build-web.mjs; WASM SHA-256 ${createHash('sha256').update(wasm).digest('hex')} -->`);
const output = new URL(pkg.sudoku.webSource, root);
if (process.argv.includes('--check')) {
  assert.equal(await readFile(output, 'utf8'), html, 'Committed application is stale; run npm run build:web');
  console.log('PASS embedded application matches source, adapter and WASM');
} else {
  await writeFile(output, html);
  console.log(`Built ${fileURLToPath(output)} (${Buffer.byteLength(html)} bytes)`);
}
